In [22]:
import pandas as pd
import numpy as np

auth_df = pd.read_csv('/Users/seanyu_mac/Downloads/public_pb_user_auth_info_export_2024-11-20_131946.csv')
user_df = pd.read_csv('/Users/seanyu_mac/Downloads/public_pb_user_export_2024-11-20_132018.csv')

user_df

,id,reg_type,email,name,sns_id,password,last_login_dt,reg_dt,upd_dt,profile_img,...,del_dt,user_tag,mobile_origin,gender,birthyear,mobile,reg_types,social_reg_info,pharmacy_title_codes,agreement_status
0,2db0d2c3-c4d1-403c-b17d-abf6a5902fec,normal,gaen1995@naver.com,가니가니,NaN,438437a6d9fa195b352d7ba57e1fbd4b3bc4efad070fae...,2023-06-09 05:05:01.967723,2023-06-09 05:05:01.967723,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[""email""]",NaN,NaN,NaN
1,115f59ad-f9fb-43d5-964d-ffabc5976f40,normal,eeskwon@naver.com,이석원,NaN,NaN,2024-03-17 06:30:07.405981,2024-03-17 06:30:07.405981,NaN,https://t1.kakaocdn.net/account_images/default...,...,NaN,NaN,+82 10-4420-7774,male,1973.0,010-4420-7774,"[""kakao""]","{""kakao"":[{""id"":""3392538751"",""name"":""이석원"",""ema...",NaN,NaN
2,ab93c274-fedc-440f-ae1e-f659db8b66b3,normal,joyu110@naver.com,즐거운천사8975,3694564115,NaN,2024-09-06 03:43:40.09,2024-09-06 03:43:40.09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[""kakao""]",NaN,NaN,NaN
3,8b006b7e-4698-4e45-8932-43435c1bd9aa,normal,jwlovenllove@naver.com,강혜령,NaN,NaN,2023-07-25 03:29:25.598058,2023-07-13 10:34:23.510532,2023-07-25 03:29:25.598058,http://k.kakaocdn.net/dn/drzkpN/btsmUIX5edZ/Vz...,...,NaN,NaN,+82 10-6816-0340,female,1987.0,010-6816-0340,"[""kakao""]","{""kakao"":[{""id"":""2909513279"",""name"":""강혜령"",""ema...","[""iam_yaksa_""]",NaN
4,b4759aff-5344-4668-9386-ae8a3ec57ca8,normal,goldfish327@kakao.com,humptyrumpty,NaN,NaN,2024-05-28 09:45:37.264701,2024-05-28 09:45:37.264701,NaN,https://k.kakaocdn.net/dn/dJGjr3/btsGTzt3DRk/j...,...,NaN,NaN,+82 10-3957-7856,male,1966.0,010-3957-7856,"[""kakao""]","{""kakao"":[{""id"":""3502348322"",""name"":""humptyrum...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25708,561e65bc-bee3-469d-a53f-d5b012eef952,normal,hss3047@naver.com,황산성,NaN,NaN,2024-07-12 11:43:38.880688,2023-12-12 01:39:17.266355,2024-11-20 00:09:35.339092,https://k.kakaocdn.net/dn/BbwEV/btrVVIoR8zv/4J...,...,NaN,NaN,+82 10-9388-3047,NaN,NaN,010-9388-3047,"[""kakao""]","{""kakao"":[{""id"":""3220329898"",""name"":""케일러"",""ema...","[""wiki_yaksa""]","{""terms"":{""campaign"":{""collect_agreement"":{""ag..."
25709,f68e2675-3107-446b-ab17-48a7b0048f71,normal,jenny2570@naver.com,오주원,NaN,NaN,2024-07-04 04:20:08.791284,2024-07-04 04:20:08.791284,2024-11-20 01:34:36.64514,https://k.kakaocdn.net/dn/dnOUye/btsH9hStsN0/v...,...,NaN,NaN,+82 10-4764-2570,NaN,NaN,010-4764-2570,"[""kakao""]","{""kakao"":[{""id"":""3607751236"",""name"":""춘아가"",""ema...",NaN,"{""terms"":{""campaign"":{""collect_agreement"":{""ag..."
25710,22335cae-5c5c-4562-82ab-a8da900bf6a2,normal,attraction2@naver.com,김진오,NaN,NaN,2023-09-22 00:47:45.348059,2023-09-22 00:47:45.348059,2024-11-20 01:37:12.012217,https://k.kakaocdn.net/dn/C2VBP/btsahLfaoG5/id...,...,NaN,NaN,+82 10-9317-1741,male,1984.0,010-9317-1741,"[""kakao""]","{""kakao"":[{""id"":""3031995089"",""name"":""김진오"",""ema...",NaN,"{""terms"":{""campaign"":{""collect_agreement"":{""ag..."
25711,b0f8321e-8fad-4977-9a25-138840824938,normal,dudwn6489@naver.com,정지윤,NaN,NaN,2023-12-26 07:48:08.290441,2023-10-31 04:25:44.576025,2023-12-26 07:48:08.290441,https://k.kakaocdn.net/dn/cMCCKF/btszuGNesdR/p...,...,NaN,NaN,+82 10-3691-4519,female,2001.0,010-3691-4519,"[""kakao""]","{""kakao"":[{""id"":""3141413322"",""name"":""쥰주"",""emai...",NaN,NaN
25712,0e9d860d-1b7d-4486-a43c-bdbad4b1c82c,normal,vigun05@daum.net,송대선,NaN,NaN,2024-07-29 15:18:40.635162,2023-09-04 15:02:12.388107,2024-11-20 03:42:38.615888,https://k.kakaocdn.net/dn/bD66Vt/btshbtxZTUl/D...,...,NaN,NaN,+82 10-6204-6527,female,1970.0,010-6204-6527,"[""kakao""]","{""kakao"":[{""id"":""3004912625"",""name"":""..."",""ema...",NaN,"{""terms"":{""campaign"":{""collect_agreement"":{""ag..."

In [4]:
auth_df['sns_type'].value_counts()

sns_type
kakao    7470
email     288
apple     271
Name: count, dtype: int64

In [14]:
271/(7470+288+271)*100

3.3752646655872462

In [10]:
user_df['reg_types'].value_counts()

reg_types
["kakao"]            24282
["apple"]              674
["email"]              660
["email","kakao"]       59
["kakao","email"]       28
Name: count, dtype: int64

In [16]:
674/(len(user_df['reg_types']))*100

2.6212421732197724

In [48]:
a = auth_df.loc[auth_df['sns_type'] == 'apple', 'id']

In [50]:
b = user_df.loc[user_df['reg_types'] == user_df['reg_types'].unique()[3], 'id']

In [54]:
df = pd.DataFrame()
df['a'] = a
df['b'] = a
df

,a,b
35,8e5a2517-7c68-4eed-b77a-a5ae48b876f0,8e5a2517-7c68-4eed-b77a-a5ae48b876f0
44,8109af77-9b02-4bf9-a7c6-57155838dfae,8109af77-9b02-4bf9-a7c6-57155838dfae
47,854c1641-16df-4979-9b5b-6079be688455,854c1641-16df-4979-9b5b-6079be688455
59,80c9174d-04e0-4b28-8f57-8eca8d9d8822,80c9174d-04e0-4b28-8f57-8eca8d9d8822
65,48b4b65e-6ca7-4d39-80fa-51bc2a7679aa,48b4b65e-6ca7-4d39-80fa-51bc2a7679aa
...,...,...
7834,17bc479d-081a-4bd5-930a-7154d9696634,17bc479d-081a-4bd5-930a-7154d9696634
7911,f1a91550-8eb9-4b30-8441-68ee238c01fe,f1a91550-8eb9-4b30-8441-68ee238c01fe
7969,3f1208ac-ec8a-4bd6-8423-eb4176dfbe62,3f1208ac-ec8a-4bd6-8423-eb4176dfbe62
7987,382a0cf4-5a1c-4632-af18-83db717db9cf,382a0cf4-5a1c-4632-af18-83db717db9cf
8007,164f9538-4628-4031-909d-b2b36b55079e,164f9538-4628-4031-909d-b2b36b55079e

In [66]:
import pandas as pd
c = []

for i in df['a']:
    if i in df['b'].values:
        c.append(i)

len(c)

271