In [447]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
import matplotlib.pyplot as plt
warnings.simplefilter('ignore')

In [525]:
df = pd.read_csv('/Users/seanyu_mac/Downloads/누적 매출_Master - raw.csv')
fs_df = pd.read_excel('/Users/seanyu_mac/Downloads/주문내역_2024-04-04~2025-04-04.xlsx')

In [527]:
df.columns = df.loc[2]
df = df.drop([0,1,2]).reset_index()
df = df[df['채널명 (쇼핑몰명)'] == '친한 스토어']

In [541]:
df = df[df['채널상품명'] == '0']

In [543]:
fs_df = fs_df[fs_df['주문 상태'].isin(['결제완료', '배송중', '배송완료', '배송준비', '구매확정'])]

In [545]:
df['실결제금액']

59362     85,500
59824    133,000
60036     96,900
60160    159,600
60161    199,500
          ...
91190     66,500
91244    112,100
91433     55,100
91720     42,740
91743     55,100
Name: 실결제금액, Length: 135, dtype: object

In [547]:
fs_df['정산가'] = fs_df['정산가'].apply(lambda x: f'{x:,}')
fs_df['실결제금액'] = fs_df['정산가'].astype(str)
fs_df['실결제금액']

0       23,750
1       42,740
2       33,250
3       16,800
4        9,900
         ...
1450    42,750
1452    23,750
1455    48,450
1461    21,370
1463    14,000
Name: 실결제금액, Length: 1139, dtype: object

In [549]:
df['주문번호'] = df['주문번호'].apply(lambda x: x[:5])
df['주문번호'] = df['주문번호'].astype(str)
df['주문번호']

59362    50352
59824    50195
60036    50196
60160    50199
60161    50199
         ...
91190    50158
91244    50160
91433    50184
91720    50193
91743    50194
Name: 주문번호, Length: 135, dtype: object

In [551]:
fs_df['주문 번호'] = fs_df['주문 번호'].apply(lambda x: x[:5])
fs_df['주문번호'] = fs_df['주문 번호'].astype(str)
fs_df['주문번호']

0       52153
1       52152
2       52151
3       52150
4       52150
        ...
1450    50016
1452    50014
1455    50012
1461    50005
1463    50003
Name: 주문번호, Length: 1139, dtype: object

In [553]:
df['주문일'] = pd.to_datetime(df['주문일'])
df['주문일'] = df['주문일'].astype(str)
df['주문일']

59362    2024-12-10 22:33:30
59824    2024-11-01 00:54:07
60036    2024-11-01 14:38:58
60160    2024-11-01 21:20:39
60161    2024-11-01 21:20:39
                ...
91190    2024-10-29 22:44:09
91244    2024-10-30 05:12:52
91433    2024-10-30 18:52:33
91720    2024-10-31 12:43:18
91743    2024-10-31 13:54:25
Name: 주문일, Length: 135, dtype: object

In [555]:
fs_df['결제 완료일'] = fs_df['결제 완료일'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S'))
fs_df['주문일'] = fs_df['결제 완료일']
fs_df['주문일']

0       2025-04-04 09:18:01
1       2025-04-04 02:46:17
2       2025-04-03 18:45:26
3       2025-04-03 17:47:45
4       2025-04-03 17:47:45
               ...
1450    2024-09-28 09:05:13
1452    2024-09-27 13:48:27
1455    2024-09-26 13:02:33
1461    2024-09-25 13:32:16
1463    2024-09-20 18:41:26
Name: 주문일, Length: 1139, dtype: object

In [573]:
fs_df

,결제 번호,상품 번호,주문 번호,결제 완료일,주문 상태,상품명,옵션명,수량,정상가,판매가,...,도서산간 배송비,취소 완료일,판매자 취소일,반품 요청일,수거 요청일,수거 완료일,반품 완료일,실결제금액,주문번호,주문일
0,parma20250404091738KV5B5,50006,52153,2025-04-04 09:18:01,결제완료,[스페셜할인코드/친한] YDY 코랄칼마디 K2 1박스(1개월분) / 칼슘 마그네슘 ...,[스페셜할인코드/친한] YDY 코랄칼마디 K2 1박스(1개월분) / 칼슘 마그네슘 ...,1,25000,23750,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"23,750",52153,2025-04-04 09:18:01
1,parma20250404024552KCbK0,50573,52152,2025-04-04 02:46:17,결제완료,[스페셜할인코드/서울약사] 썬비타민D3&K2 1박스,[스페셜할인코드/서울약사] 썬비타민D3&K2 1박스,2,25000,21370,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"42,740",52152,2025-04-04 02:46:17
2,parma20250403184417LxuG4,50002,52151,2025-04-03 18:45:26,결제완료,[스페셜할인코드/친한] YDY 액티브비큐텐 1박스(1개월분),[스페셜할인코드/친한] YDY 액티브비큐텐 1박스(1개월분),1,35000,33250,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"33,250",52151,2025-04-03 18:45:26
3,parma20250403174717yazD9,50425,52150,2025-04-03 17:47:45,결제완료,임직원용 PB 상품 구매 페이지,퓨어리포좀글루타치온,1,59000,16800,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"16,800",52150,2025-04-03 17:47:45
4,parma20250403174717yazD9,50425,52150,2025-04-03 17:47:45,결제완료,임직원용 PB 상품 구매 페이지,폴라초임계오메가3,1,28000,9900,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"9,900",52150,2025-04-03 17:47:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,parma20240928090515CkfQ2,50085,50016,2024-09-28 09:05:13,구매확정,[스페셜할인코드/남기헌약사] YDY 프로바이오 에스엘비 1박스(2개월분),[스페셜할인코드/남기헌약사] YDY 프로바이오 에스엘비 1박스(2개월분),1,45000,42750,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"42,750",50016,2024-09-28 09:05:13
1452,parma20240927134828DZU39,50006,50014,2024-09-27 13:48:27,구매확정,[스페셜할인코드/친한] YDY 코랄칼마디 K2 1박스(1개월분) / 칼슘 마그네슘 ...,[스페셜할인코드/친한] YDY 코랄칼마디 1박스(1개월분) / 칼슘 마그네슘 비타민D,1,25000,23750,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"23,750",50014,2024-09-27 13:48:27
1455,parma20240926130234OzMz1,50012,50012,2024-09-26 13:02:33,구매확정,[스페셜할인코드/친한] YDY 파이토 레드큐민 1박스(1개월분) /커큐민,[스페셜할인코드/친한] YDY 파이토 레드큐민 1박스(1개월분) /커큐민,1,51000,48450,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"48,450",50012,2024-09-26 13:02:33
1461,parma20240925133216CVxv5,50009,50005,2024-09-25 13:32:16,구매확정,[스페셜할인코드/친한] YDY 풀스펙멀티비타민 1박스(1개월분),[스페셜할인코드/친한] YDY 풀스펙멀티비타민 1박스(1개월분),1,22500,21370,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"21,370",50005,2024-09-25 13:32:16
1463,parma20240920184127cDyU0,50000,50003,2024-09-20 18:41:26,구매확정,[스페셜할인코드/친한] YDY 폴라초임계오메가3 1박스 (1개월분),[스페셜할인코드/친한] YDY 폴라초임계오메가3 1박스 (1개월분),1,28000,14000,...,0,NaT,NaT,NaT,NaT,NaT,NaT,"14,000",50003,2024-09-20 18:41:26

In [575]:
fs_df_dedup = fs_df.drop_duplicates(subset=['주문번호', '주문일'])

merge_df = pd.merge(df[['실결제금액', '주문번호', '주문일']], fs_df_dedup[['실결제금액', '주문번호', '주문일', '상품명', '옵션명', '상품 번호']], on=['주문번호', '주문일'], how='left')

In [577]:
merge_df

,실결제금액_x,주문번호,주문일,실결제금액_y,상품명,옵션명,상품 번호
0,"85,500",50352,2024-12-10 22:33:30,"42,750",[스페셜할인코드/친한] YDY 프로바이오 에스엘비 1박스(2개월분),[스페셜할인코드/친한] YDY 프로바이오 에스엘비 1박스(2개월분),50005
1,"133,000",50195,2024-11-01 00:54:07,"66,500",[스페셜할인코드/친한] YDY 액티브비큐텐 1박스(1개월분),[스페셜할인코드/친한] YDY 액티브비큐텐 1박스(1개월분),50002
2,"96,900",50196,2024-11-01 14:38:58,"48,450",[스페셜할인코드/친한] YDY 파이토 레드큐민 1박스(1개월분) /커큐민,[스페셜할인코드/친한] YDY 파이토 레드큐민 1박스(1개월분) /커큐민,50012
3,"159,600",50199,2024-11-01 21:20:39,"71,250",[스페셜할인코드/친한] YDY 마그듀오 K2 1박스(1개월분),[스페셜할인코드/친한] YDY 마그듀오 1박스(1개월분),50003
4,"199,500",50199,2024-11-01 21:20:39,"71,250",[스페셜할인코드/친한] YDY 마그듀오 K2 1박스(1개월분),[스페셜할인코드/친한] YDY 마그듀오 1박스(1개월분),50003
...,...,...,...,...,...,...,...
130,"66,500",50158,2024-10-29 22:44:09,"33,250",[스페셜할인코드/고상온약사] YDY 액티브비큐텐 1박스(1개월분),[스페셜할인코드/고상온약사] YDY 액티브비큐텐 1박스(1개월분),50022
131,"112,100",50160,2024-10-30 05:12:52,"56,050",[스페셜할인코드/고상온약사] YDY 퓨어리포좀글루타치온 1박스 (30일분),[스페셜할인코드/고상온약사] YDY 퓨어리포좀글루타치온 1박스 (30일분),50027
132,"55,100",50184,2024-10-30 18:52:33,"27,550",[스페셜할인코드/친한] YDY 퓨어리포좀비타민C 1박스(1개월분),[스페셜할인코드/친한] YDY 퓨어리포좀비타민C 1박스(1개월분),50014
133,"42,740",50193,2024-10-31 12:43:18,"21,370",[스페셜할인코드/친한] YDY 풀스펙멀티비타민 1박스(1개월분),[스페셜할인코드/친한] YDY 풀스펙멀티비타민 1박스(1개월분),50009
134,"55,100",50194,2024-10-31 13:54:25,"27,550",[스페셜할인코드/친한] YDY 퓨어리포좀비타민C 1박스(1개월분),[스페셜할인코드/친한] YDY 퓨어리포좀비타민C 1박스(1개월분),50014

In [579]:
merge_df = merge_df.sort_values(by='주문일', ascending=True)
merge_df.to_excel('/Users/seanyu_mac/Downloads/주문내역345432543254-04.xlsx')