In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

df = pd.read_csv('/Users/seanyu_mac/Downloads/query_1-2025-01-09_110709.csv')
df[['upsert_dt', 'order_option', '']]

,id,group_buy_id,order_no,order_ymd_hms,order_ymd,order_hour,order_status,order_option,order_count,box_count,order_person,order_mapping_name,order_price,is_valid,invalid_reason,reg_dt,upsert_dt,upsert_before
0,1141284,970,2025010641051401,20250106003652,20250106,0,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-06 07:02:35.046186,2025-01-09 01:39:59.364603,NaN
1,1141285,970,2025010639570071,20250106000029,20250106,0,배송완료,구성: 15포 X 8박스,2,8,NaN,8박스,176000,Y,NaN,2025-01-06 07:02:35.046186,2025-01-09 01:39:59.364603,NaN
2,1148823,970,2025010642420161,20250106011118,20250106,1,배송완료,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
3,1148824,970,2025010642189401,20250106010524,20250106,1,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
4,1148822,970,2025010645108361,20250106022407,20250106,2,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,1164016,970,2025010816661421,20250108193102,20250108,19,배송중,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
80,1164017,970,2025010816618581,20250108192959,20250108,19,배송중,구성: 15포 X 8박스,1,8,NaN,8박스,88000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
81,1164014,970,2025010822414031,20250108214645,20250108,21,배송중,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
82,1164015,970,2025010820785181,20250108210428,20250108,21,배송중,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
83,1164011,970,2025010952004111,20250109180942,20250109,18,결제완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN

In [10]:
from datetime import datetime
import pytz

# 베이지 약사 최초 엑셀 업로드 시 주문 일시
timestamp_excel = '2025. 1. 6 오후 3:36:52'
print(f'최초 엑셀 파일을 커머스팀이 업로드할 때 주문일시가 {timestamp_excel}')
# 파마브로스 어드민에 위 주문일시의 건을 업로드 했을 때, admin_group_buy_excel_order의 order_ymd_hms 의 값
timestamp_order = "20250106003652"
print(f'그게 파마브로스 어드민 그룹 바이 엑셀 오더에는 {timestamp_order}')
dt_timestamp_order = datetime.strptime(timestamp_order, "%Y%m%d%H%M%S")

# 파마브로스의 order_ymd_hms값을 바꿔보자
local_tz = pytz.timezone("Asia/Seoul")
dt_localized = local_tz.localize(dt_timestamp_order)
dt_utc = dt_timestamp_order.astimezone(pytz.utc)

print(dt_localized) 
print(dt_utc)

최초 엑셀 파일을 커머스팀이 업로드할 때 주문일시가 2025. 1. 6 오후 3:36:52
그게 파마브로스 어드민 그룹 바이 엑셀 오더에는 20250106003652
2025-01-06 00:36:52+09:00
2025-01-05 15:36:52+00:00

In [14]:
from datetime import datetime
import pytz

# 베이지 약사 최초 엑셀 업로드 시 주문 일시
timestamp_excel = '2025/01/06 15:00'
print(f'최초 엑셀 파일을 커머스팀이 업로드할 때 주문일시가 {timestamp_excel}')
# 파마브로스 어드민에 위 주문일시의 건을 업로드 했을 때, admin_group_buy_excel_order의 order_ymd_hms 의 값
timestamp_order = "20250106000029"
print(f'그게 파마브로스 어드민 그룹 바이 엑셀 오더에는 {timestamp_order}')
dt_timestamp_order = datetime.strptime(timestamp_order, "%Y%m%d%H%M%S")

# 파마브로스의 yyddmmhhmmss 값을 바꿔보자
local_tz = pytz.timezone("Asia/Seoul")
dt_localized = local_tz.localize(dt_timestamp_order)
dt_utc = dt_timestamp_order.astimezone(pytz.utc)

print(dt_localized) 
print(dt_utc)

최초 엑셀 파일을 커머스팀이 업로드할 때 주문일시가 2025/01/06 15:00
그게 파마브로스 어드민 그룹 바이 엑셀 오더에는 20250106000029
2025-01-06 00:00:29+09:00
2025-01-05 15:00:29+00:00

In [12]:
df['']

,id,group_buy_id,order_no,order_ymd_hms,order_ymd,order_hour,order_status,order_option,order_count,box_count,order_person,order_mapping_name,order_price,is_valid,invalid_reason,reg_dt,upsert_dt,upsert_before
0,1141284,970,2025010641051401,20250106003652,20250106,0,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-06 07:02:35.046186,2025-01-09 01:39:59.364603,NaN
1,1141285,970,2025010639570071,20250106000029,20250106,0,배송완료,구성: 15포 X 8박스,2,8,NaN,8박스,176000,Y,NaN,2025-01-06 07:02:35.046186,2025-01-09 01:39:59.364603,NaN
2,1148823,970,2025010642420161,20250106011118,20250106,1,배송완료,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
3,1148824,970,2025010642189401,20250106010524,20250106,1,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
4,1148822,970,2025010645108361,20250106022407,20250106,2,배송완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-07 01:59:17.040711,2025-01-09 01:39:59.364603,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,1164016,970,2025010816661421,20250108193102,20250108,19,배송중,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
80,1164017,970,2025010816618581,20250108192959,20250108,19,배송중,구성: 15포 X 8박스,1,8,NaN,8박스,88000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
81,1164014,970,2025010822414031,20250108214645,20250108,21,배송중,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
82,1164015,970,2025010820785181,20250108210428,20250108,21,배송중,구성: 15포 X 4박스,1,4,NaN,4박스,55000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN
83,1164011,970,2025010952004111,20250109180942,20250109,18,결제완료,구성: 15포 X 2박스,1,2,NaN,2박스,31000,Y,NaN,2025-01-09 01:39:59.364603,2025-01-09 01:39:59.364603,NaN