In [118]:
import pandas as pd

excel_df = pd.read_excel('/Users/seanyu_mac/Downloads/20250110 1000 슈퍼맘약사 알래스카츄 주문내역.xlsx')
pb_df = pd.read_csv('/Users/seanyu_mac/Downloads/public_admin_group_buy_excel_order_export_2025-01-10_161638.csv')
con1 = excel_df['옵션명'] == '수량 : 알래스카 츄어블: 2박스 (4개월)'
con2 = excel_df['옵션명'] == '수량 : 알래스카 츄어블: 4박스 (8개월)'
con3 = excel_df['옵션명'] == '수량 : 알래스카 츄어블: 6박스 (12개월)'
excel_df['price'] = 0
excel_df['sales'] = 0
excel_df.loc[con1, 'price'] = 84000
excel_df.loc[con2, 'price'] = 159000
excel_df.loc[con3, 'price'] = 229000
excel_df['sales'] = excel_df['price'] * excel_df['구매수량']

In [120]:
from datetime import datetime, timedelta

excel_df['주문일'] = pd.to_datetime(excel_df['주문일'])
excel_df

,주문번호,주문일,주문상태,옵션명,구매수량,price,sales
0,202501101372682,2025-01-10 10:00:55,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
1,202501107971278,2025-01-10 09:59:31,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
2,202501108582176,2025-01-10 09:52:30,거래개시,수량 : 알래스카 츄어블: 4박스 (8개월),1,159000,159000
3,202501106611672,2025-01-10 09:50:29,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
4,202501105483586,2025-01-10 09:18:36,거래개시,수량 : 알래스카 츄어블: 4박스 (8개월),1,159000,159000
...,...,...,...,...,...,...,...
133,202501096362730,2025-01-09 00:59:58,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
134,202501096557280,2025-01-09 00:52:51,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
135,202501092749499,2025-01-09 00:49:16,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000
136,202501095055657,2025-01-09 00:24:03,거래개시,수량 : 알래스카 츄어블: 4박스 (8개월),1,159000,159000
137,202501097301950,2025-01-09 00:22:09,거래개시,수량 : 알래스카 츄어블: 2박스 (4개월),1,84000,84000

In [148]:
df_30 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='30T'))['sales'].sum().reset_index())
df_60 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='1H'))['sales'].sum().reset_index())
df_180 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='3H'))['sales'].sum().reset_index())
df_360 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='6H'))['sales'].sum().reset_index())
df_day = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='1D'))['sales'].sum().reset_index())
df_week = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='W'))['sales'].sum().reset_index())
df_month = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='M'))['sales'].sum().reset_index())

/var/folders/wl/txjbcgld2sngchsc7txxqppm0000gp/T/ipykernel_44534/2262614349.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df_30 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='30T'))['sales'].sum().reset_index())
/var/folders/wl/txjbcgld2sngchsc7txxqppm0000gp/T/ipykernel_44534/2262614349.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_60 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='1H'))['sales'].sum().reset_index())
/var/folders/wl/txjbcgld2sngchsc7txxqppm0000gp/T/ipykernel_44534/2262614349.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_180 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='3H'))['sales'].sum().reset_index())
/var/folders/wl/txjbcgld2sngchsc7txxqppm0000gp/T/ipykernel_44534/2262614349.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_360 = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='6H'))['sales'].sum().reset_index())
/var/folders/wl/txjbcgld2sngchsc7txxqppm0000gp/T/ipykernel_44534/2262614349.py:7: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_month = pd.DataFrame(excel_df.groupby(pd.Grouper(key='주문일', freq='M'))['sales'].sum().reset_index())

In [150]:
with pd.ExcelWriter("/Users/seanyu_mac/Downloads/슈퍼맘약사시간별데이터.xlsx") as writer:
    df_30.to_excel(writer, sheet_name="df_30", index=False)
    df_60.to_excel(writer, sheet_name="df_60", index=False)
    df_180.to_excel(writer, sheet_name="df_180", index=False)
    df_360.to_excel(writer, sheet_name="df_360", index=False)
    df_day.to_excel(writer, sheet_name="df_day", index=False)
    df_week.to_excel(writer, sheet_name="df_week", index=False)
    df_month.to_excel(writer, sheet_name="df_month", index=False)