In [7]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [11]:
df = pd.read_excel('/Users/seanyu_mac/Downloads/주문내역_2024-02-12~2025-02-12.xlsx')

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [13]:
df.head(3)

,결제 번호,상품 번호,주문 번호,결제 완료일,주문 상태,상품명,옵션명,수량,정상가,판매가,...,송장 번호,배송비 정책,배송비,도서산간 배송비,취소 완료일,판매자 취소일,반품 요청일,수거 요청일,수거 완료일,반품 완료일
0,parma20250212162823761J1,50554,50533-50670,2025-02-12 16:29:21.159,취소완료,[라이브 테스트] 공동구매 상품,옵션_1,1,50000,1000,...,NaN,무료배송,0,0,2025-02-12 16:35:04.652,NaT,NaT,NaT,NaT,NaT
1,parma20250212162823761J1,50554,50533-50671,2025-02-12 16:29:21.159,취소완료,[라이브 테스트] 공동구매 상품,옵션_3,1,70000,3000,...,NaN,무료배송,0,0,2025-02-12 16:35:04.652,NaT,NaT,NaT,NaT,NaT
2,parma20250212145230cWwB3,50425,50531-50669,2025-02-12 14:52:49.443,취소완료,임직원용 PB 상품 구매 페이지,폴라초임계오메가3,1,28000,9900,...,NaN,"3,000원 (30,000원 이상 구매시 무료 배송)",0,0,2025-02-12 14:54:33.791,NaT,NaT,NaT,NaT,NaT

In [55]:
a = df.columns.tolist()
b = list(range(df.columns.size))
dict(zip(a, b))

{'결제 번호': 0,
 '상품 번호': 1,
 '주문 번호': 2,
 '결제 완료일': 3,
 '주문 상태': 4,
 '상품명': 5,
 '옵션명': 6,
 '수량': 7,
 '정상가': 8,
 '판매가': 9,
 '쿠폰 할인': 10,
 '포인트 할인': 11,
 '적립금': 12,
 '정산가': 13,
 '수령인명': 14,
 '수령인 연락처': 15,
 '구매자명': 16,
 '구매자 ID': 17,
 '구매자 연락처': 18,
 '주소': 19,
 '우편번호': 20,
 '배송 메모': 21,
 '주문 확인일': 22,
 '발주 요청일': 23,
 '배송 완료일': 24,
 '구매 확정일': 25,
 '배송택배사': 26,
 '송장 번호': 27,
 '배송비 정책': 28,
 '배송비': 29,
 '도서산간 배송비': 30,
 '취소 완료일': 31,
 '판매자 취소일': 32,
 '반품 요청일': 33,
 '수거 요청일': 34,
 '수거 완료일': 35,
 '반품 완료일': 36}

In [29]:
con1 = df.iloc[:, 14] == '장혜옥'
con2 = df.iloc[:, 16] == '장혜옥'
df[con1 | con2]

,결제 번호,상품 번호,주문 번호,결제 완료일,주문 상태,상품명,옵션명,수량,정상가,판매가,...,송장 번호,배송비 정책,배송비,도서산간 배송비,취소 완료일,판매자 취소일,반품 요청일,수거 요청일,수거 완료일,반품 완료일
320,parma20240930163122KO5m2,50025,50024-50031,2024-09-30 16:31:21.706,구매확정,[스페셜할인코드/고상온약사] YDY 프로바이오 에스엘비 1박스(2개월분),[스페셜할인코드/고상온약사] YDY 프로바이오 에스엘비 1박스(2개월분),1,45000,42750,...,5.337150e+11,"3,000원 (30,000원 이상 구매시 무료 배송)",0,0,NaT,NaT,NaT,NaT,NaT,NaT
321,parma20240930163122KO5m2,50022,50024-50032,2024-09-30 16:31:21.706,구매확정,[스페셜할인코드/고상온약사] YDY 액티브비큐텐 1박스(1개월분),[스페셜할인코드/고상온약사] YDY 액티브비큐텐 1박스(1개월분),1,35000,33250,...,5.337150e+11,"3,000원 (30,000원 이상 구매시 무료 배송)",0,0,NaT,NaT,NaT,NaT,NaT,NaT

In [31]:
con1 = df.iloc[:, 14] == '피영근'
con2 = df.iloc[:, 16] == '피영근'
df[con1 | con2]

Empty DataFrame
Columns: [결제 번호, 상품 번호, 주문 번호, 결제 완료일, 주문 상태, 상품명, 옵션명, 수량, 정상가, 판매가, 쿠폰 할인, 포인트 할인, 적립금, 정산가, 수령인명, 수령인 연락처, 구매자명, 구매자 ID, 구매자 연락처, 주소, 우편번호, 배송 메모, 주문 확인일, 발주 요청일, 배송 완료일, 구매 확정일, 배송택배사, 송장 번호, 배송비 정책, 배송비, 도서산간 배송비, 취소 완료일, 판매자 취소일, 반품 요청일, 수거 요청일, 수거 완료일, 반품 완료일]
Index: []

[0 rows x 37 columns]

In [33]:
con1 = df.iloc[:, 14] == '전순안'
con2 = df.iloc[:, 16] == '전순안'
df[con1 | con2]

Empty DataFrame
Columns: [결제 번호, 상품 번호, 주문 번호, 결제 완료일, 주문 상태, 상품명, 옵션명, 수량, 정상가, 판매가, 쿠폰 할인, 포인트 할인, 적립금, 정산가, 수령인명, 수령인 연락처, 구매자명, 구매자 ID, 구매자 연락처, 주소, 우편번호, 배송 메모, 주문 확인일, 발주 요청일, 배송 완료일, 구매 확정일, 배송택배사, 송장 번호, 배송비 정책, 배송비, 도서산간 배송비, 취소 완료일, 판매자 취소일, 반품 요청일, 수거 요청일, 수거 완료일, 반품 완료일]
Index: []

[0 rows x 37 columns]

In [37]:
df[df.iloc[:, 20] == 10310]

Empty DataFrame
Columns: [결제 번호, 상품 번호, 주문 번호, 결제 완료일, 주문 상태, 상품명, 옵션명, 수량, 정상가, 판매가, 쿠폰 할인, 포인트 할인, 적립금, 정산가, 수령인명, 수령인 연락처, 구매자명, 구매자 ID, 구매자 연락처, 주소, 우편번호, 배송 메모, 주문 확인일, 발주 요청일, 배송 완료일, 구매 확정일, 배송택배사, 송장 번호, 배송비 정책, 배송비, 도서산간 배송비, 취소 완료일, 판매자 취소일, 반품 요청일, 수거 요청일, 수거 완료일, 반품 완료일]
Index: []

[0 rows x 37 columns]

In [28]:
df['reg_dt'] = pd.to_datetime(df['reg_dt'])
df['upsert_dt'] = pd.to_datetime(df['upsert_dt'])
df['reg_day'] = df['reg_dt'].dt.date

In [49]:
df['reg_day'] = pd.to_datetime(df['reg_day'])
con1 = df['reg_day'] >= datetime(2024, 1, 1)
con2 = df['reg_day'] <= datetime(2024, 12, 31)
temp_df = df.loc[con1 & con2]

In [59]:
temp_df.index.size / 12

21725.75

In [69]:
df[df.iloc[:, 20].isna()].bv

array([['parma20241113140714ntO84', 50042, '50247-50330',
        Timestamp('2024-11-13 14:07:14.129000'), '취소완료',
        '[스페셜할인코드/안재돈약사] YDY 퓨어리포좀글루타치온 1박스 (30일분)',
        '[스페셜할인코드/안재돈약사] YDY 퓨어리포좀글루타치온 1박스 (30일분)', 1, 59000, 56050, 0,
        0, 0, 56050, nan, nan, nan, nan, nan, ' ', nan, nan, NaT, NaT,
        NaT, NaT, nan, nan, '3,000원 (30,000원 이상 구매시 무료 배송)', 0, 0,
        Timestamp('2024-11-13 14:07:51.610000'), NaT, NaT, NaT, NaT, NaT]],
      dtype=object)